require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

inherit_gem:
  standard: config/base.yml
  pundit: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8
